# Generated by Django 3.2.9 on 2022-02-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserToPasswordRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('password', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('token', models.CharField(blank=True, max_length=150, null=True)),
                ('site_access', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
