# Generated by Django 4.0 on 2021-12-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='win_rate',
            field=models.FloatField(null=True),
        ),
    ]
