# Generated by Django 3.2.9 on 2022-03-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_telegramusertopasswordrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusertopasswordrelation',
            name='site_access',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='telegramusertopasswordrelation',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
