# Generated by Django 4.0 on 2021-12-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_user_win_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_games',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wins',
            field=models.IntegerField(null=True),
        ),
    ]
